version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb

  ml-service:
    build: ./ml-service
    ports:
      - "5001:5001"
    volumes:
      - ./ml-service:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=src/app.py

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: